export const categories = [
  'Văn học',
  'Kinh tế',
  'Thiếu nhi',
  'Kỹ năng sống',
  'Truyện tranh',
  'Ngoại ngữ',
  'Lịch sử',
];

export const books = [
  {
    id: 1,
    title: 'Nhà giả kim',
    author: 'Paulo Coelho',
    category: 'Văn học',
    price: 79000,
    discount: 20,
    rating: 4.8,
    isNew: false,
    color: '#E9B96E',
    emoji: '☀',
    description:
      'Hành trình theo đuổi ước mơ, khám phá thế giới và lắng nghe tiếng nói của trái tim. Một câu chuyện truyền cảm hứng về sự kiên trì và niềm tin vào bản thân.',
  },
  {
    id: 2,
    title: 'Đắc nhân tâm',
    author: 'Dale Carnegie',
    category: 'Kỹ năng sống',
    price: 98000,
    discount: 15,
    rating: 4.7,
    isNew: false,
    color: '#B5D5E8',
    emoji: '✦',
    description:
      'Những nguyên tắc giao tiếp, ứng xử và xây dựng mối quan hệ tích cực trong cuộc sống hằng ngày, được trình bày ngắn gọn và dễ áp dụng.',
  },
  {
    id: 3,
    title: 'Tuổi trẻ đáng giá bao nhiêu?',
    author: 'Rosie Nguyễn',
    category: 'Kỹ năng sống',
    price: 85000,
    discount: 0,
    rating: 4.6,
    isNew: true,
    color: '#EAC0C0',
    emoji: '❀',
    description:
      'Những chia sẻ về học tập, trải nghiệm, đọc sách và phát triển bản thân dành cho người trẻ đang tìm hướng đi của riêng mình.',
  },
  {
    id: 4,
    title: 'Dế Mèn phiêu lưu ký',
    author: 'Tô Hoài',
    category: 'Thiếu nhi',
    price: 65000,
    discount: 10,
    rating: 4.9,
    isNew: false,
    color: '#B9D5AD',
    emoji: '✿',
    description:
      'Chuyến phiêu lưu của Dế Mèn cùng những bài học về tình bạn, lòng dũng cảm và trách nhiệm trong thế giới tuổi thơ giàu tưởng tượng.',
  },
  {
    id: 5,
    title: 'Tư duy nhanh và chậm',
    author: 'Daniel Kahneman',
    category: 'Kinh tế',
    price: 189000,
    discount: 20,
    rating: 4.8,
    isNew: false,
    color: '#D0C3E9',
    emoji: '◈',
    description:
      'Khám phá hai hệ thống tư duy và cách con người đưa ra quyết định trong nhiều tình huống, từ lựa chọn cá nhân đến kinh tế hành vi.',
  },
  {
    id: 6,
    title: 'Hoàng tử bé',
    author: 'Antoine de Saint-Exupéry',
    category: 'Văn học',
    price: 72000,
    discount: 0,
    rating: 4.9,
    isNew: true,
    color: '#F1DBA5',
    emoji: '★',
    description:
      'Câu chuyện giàu chất thơ về tình yêu, tình bạn và cách nhìn thế giới bằng trái tim, phù hợp cho cả thiếu nhi lẫn người lớn.',
  },
  {
    id: 7,
    title: 'English Grammar in Use',
    author: 'Raymond Murphy',
    category: 'Ngoại ngữ',
    price: 155000,
    discount: 12,
    rating: 4.7,
    isNew: false,
    color: '#BBD9CF',
    emoji: 'A',
    description:
      'Tài liệu ngữ pháp tiếng Anh thực hành với bài học ngắn, ví dụ rõ ràng và bài tập tự luyện phù hợp cho người học trung cấp.',
  },
  {
    id: 8,
    title: 'Lược sử Việt Nam bằng tranh',
    author: 'Nhiều tác giả',
    category: 'Lịch sử',
    price: 118000,
    discount: 0,
    rating: 4.5,
    isNew: true,
    color: '#F0C6A8',
    emoji: '◆',
    description:
      'Các giai đoạn lịch sử Việt Nam được kể lại qua tranh minh họa và phần tóm tắt dễ đọc, giúp người học ghi nhớ mốc sự kiện tốt hơn.',
  },
];

export const cart = [
  {id: 1, quantity: 2},
  {id: 2, quantity: 1},
  {id: 4, quantity: 1},
];
